<?php 
// $Id: explorer8_mode.module,v 1.1.2.2 2010/05/07 00:51:04 quiptime Exp $

/**
 * @file
 * With "Explorer 8 Mode" can be defined how the Internet Explorer 8 displays all pages of an Drupal installation.
 */

/**
 * Implementation of hook_help().
 */
function explorer8_mode_help($path, $arg) {
  $output = '<h3>' . t('About') . '</h3>';
  $output .= '<p>' . t('With "Explorer 8 Mode" can be defined how the Internet Explorer 8 displays all pages from this Drupal installation.') . ' ';
  $output .= t('More information about the Document Compatibility Mode: <a href="@whats-new-url">@whats-new</a>', array('@whats-new' => t("What's New in Internet Explorer 8"), '@whats-new-url' => url('http://msdn.microsoft.com/en-us/library/cc288472(VS.85).aspx#compat'))) . '</p>';
  $output .= '<h3>' . t('Uses') . '</h3>';
  $output .= '<dl>';
  $output .= '<dt>' . t('Which mode to use for Explorer 7?') . '</dt>';
  $output .= '<dd>' . t('In order to use the Explorer 8 as the Explorer 7, you choose the mode <em>Emulate IE 7</em>.') . '</dd>';
  $output .= '</dl>';
  switch ($path) {
    case 'admin/help#explorer8_mode':
      return $output;
    case 'admin/settings/explorer8_mode':
      return '<p>'. t('With "Explorer 8 Mode" can be defined how the Internet Explorer 8 displays all pages from this Drupal installation.') .'</p>';
  }
}

/**
 * Implementation of hook_init().
 */
function explorer8_mode_init() {
  _explorer8_mode_header();
}

/**
 * Implementation of hook_menu().
 */
function explorer8_mode_menu() {
  $items = array();
  $items['admin/settings/explorer8_mode'] = array(
    'title' => 'Explorer 8 Mode',
    'description' => "Setting the document compatibility mode of the Internet Explorer 8's.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('explorer8_mode_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'explorer8_mode.admin.inc',
  );
  return $items;
}

/**
 * Help function to generate the HTML meta tag.
 *
 * @see explorer8_mode_init()
 */
function _explorer8_mode_header() {
  if (variable_get('explorer8_mode_setting', '') == 'IE=8') {
    return '';
  }
  else {
    $data = '<meta http-equiv="X-UA-Compatible" content="'. variable_get('explorer8_mode_setting', 'IE=8') .'" />';
    drupal_set_html_head($data);
  }
}
