<?php
// $id:

/**
 * @file
 * This module provides profile information about the users Soundcloud profile.
 */

/**
 * implementation of hook_theme()
 */
function soundcloud_theme($existing, $type, $theme, $path) {
  return array(
    'soundcloud_profile' =>  array(
      'arguments' => array('profile' => NULL)),
    'recent_tracks' =>  array(
      'arguments' => array('username' => NULL)),
    'dropbox' =>  array(
      'arguments' => array('username' => NULL))
    );
}

/**
 * hook_user()
 * Provide basic soundcloud information on the user profile page
 */
function soundcloud_profile_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'view' && soundcloud_check_token($account->uid)) {
    if (soundcloud_view_profile_permission($account->uid)) {
      if (!isset($account->content['soundcloud'])) {
        $account->content['soundcloud'] = array(
          '#attributes' => array('class' => 'user-member'),
          '#title'      => t('SoundCloud'),
          '#type'       => 'user_profile_category',
          '#weight'     => 5,
        );
      }
      $profile = soundcloud_me($account->uid);
      $value = theme('soundcloud_profile', $profile);
      $account->content['soundcloud']['profile'] = array(
        '#title'      => '',
        '#type'       => 'user_profile_item',
        '#value'      => $value,
        '#weight'     => 1,
      );
    }
  }
}

/**
 * Theme function generating the player code.
 * @username
 *  The soundcloud username of the user
 * @player
 *  The Soundcloud player with all the songs of the user
 */
function theme_soundcloud_profile($profile) {
  $output = '<div id="soundcloud-profile">';
  $output .= '<h3>' . t('SoundCloud Profile of !username', array('!username' => l($profile['username'], $profile['permalink-url']))) . '</h3>';
  $output .= theme('dropbox', $profile['permalink']);
  $output .= theme('recent_tracks', $profile['permalink']);
  $output .= '</div>';
  return $output;
}

/**
 * Theming funtion to create the latest track player from soundcloud.
 * @param $username
 *  the soundcloud username
 */
function theme_recent_tracks($username) {
  $output  = '<h3>Latest tracks</h3>';
  $output .= '<object width="100%" height="225">';
  $output .= '<param value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F' . $username . '" name="movie">';
  $output .= '<param value="always" name="allowscriptaccess">';
  $output .= '<embed width="100%" height="225" type="application/x-shockwave-flash" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F' . $username . '" allowscriptaccess="always">';
  $output .= '</object>';
  return $output;
}

/**
 * Theming function to create a dropbox icon on the user profile.
 * @param $username
 *  the soundcloud username
 */
function theme_dropbox($username) {
  $output .= '<a class="soundcloud-dropbox" style="display: block; background: url(&quot;http://a1.soundcloud.com/images/dropbox_small_dark.png?9aecec&quot;) no-repeat scroll left top transparent; color: rgb(217, 217, 217); font-size: 10px; height: 30px; padding: 26px 60px 0pt 12px; width: 127px; text-decoration: none; font-family: &quot;Lucida Grande&quot;,Helvetica,Arial,sans-serif; line-height: 1.3em;" href="http://soundcloud.com/' . $username . '/dropbox">Send me your track</a>';
  return $output;
}